source :gemcutter

git "git://github.com/rails/rails.git"
gem "rake"
gem "jeweler"
gem "shoulda"
gem "activesupport",     "~> 3.0.0.beta1", :require => "active_support"
gem "data_objects",      "~> 0.10.1"
gem "do_sqlite3"
gem "dm-do-adapter",                       :git => "git://github.com/datamapper/dm-do-adapter.git"
gem "dm-sqlite-adapter",                   :git => "git://github.com/datamapper/dm-sqlite-adapter.git"
gem "dm-aggregates",                       :git => "git://github.com/datamapper/dm-aggregates.git"
gem "dm-migrations",                       :git => "git://github.com/datamapper/dm-migrations.git", :ref => "6b04a98e3e4ad5c57b19"
gem "dm-timestamps",                       :git => "git://github.com/datamapper/dm-timestamps.git"
gem "dm-transactions",                     :git => "git://github.com/datamapper/dm-transactions.git"
gem "dm-types",                            :git => "git://github.com/datamapper/dm-types.git"
gem "dm-validations",                      :git => "git://github.com/datamapper/dm-validations.git"
gem "dm-aggregates",                       :git => "git://github.com/datamapper/dm-aggregates.git"
gem "dm-constraints",                      :git => "git://github.com/datamapper/dm-constraints.git"
gem "dm-observer",                         :git => "git://github.com/datamapper/dm-observer.git"
gem "dm-core",                             :git => "git://github.com/datamapper/dm-core.git", :ref => "bcb619087d813f576e23"